### ISSUE TITLE
این ترجمه چاپ شده؟

### ISSUE THREAD

**Issue by HassanHeydariNasab** [ThinkPythonPersian/thinkbook#1]
سلام
چند هفته پیش ترجمهٔ چاپ شده‌ای از این کتاب از کتاب‌خونه امانت گرفته بودم.
یادم نیست همین بود یا نه.
گفتم که در جریان باشید :)

**Comment by ShalbafZadeh** [comment]
سلام

ترجمه ی ما چاپ نشده ولی یک ترجمه دیگه از این کتاب چاپ شده
کتاب لایسنس خیلی خوبی داره که اجازه ترجمه و نشر رو میده 
ممنونم که گفتید :)
